project:
  type: website

website:
  title: "explo"
  navbar:
    left:
      - href: perf.qmd
        text: Performance

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



