project:
  type: website

website:
  title: "explo"
  navbar:
    left:
      - href: stats-desc.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



